### PR TITLE
Fix typo in IAsyncNetworkChannel open? documentation

### PR DESCRIPTION
**Pull request by thenonameguy**

### CODE REVIEW

**Comment by danielcompton** [comment]
I'm not sure if this is a typo, I read it as "if and only if". Peter will know though.

**Comment by ptaoussanis** [comment]
Hi Szabó, thanks for taking the time on this. Daniel's correct, this isn't a typo: https://en.wikipedia.org/wiki/If_and_only_if

(Thanks @danielcompton!)

Hope that helps? Cheers :-)

**Comment by danielcompton** [comment]
I'll close this.

**Comment by thenonameguy** [comment]
Oh I see, TIL, thanks!

**Pull request closed without merging**
