### PR TITLE
README fix: wherefore means why, not where.

### PR DESCRIPTION
**Pull request by ane**
http://www.oed.com/view/Entry/228218

### CODE REVIEW

**Comment by ane** [comment]
In case the link doesn't work: http://en.wiktionary.org/wiki/wherefore

**Comment by ptaoussanis** [comment]
That's my sense of humour apparently not communicating too well ;-)

**Comment by ane** [comment]
Oh. Ahem.

**Comment by ptaoussanis** [comment]
No problem, never hurts to check :-)

**Pull request closed without merging**
