### PR TITLE
Added new example for System

### PR DESCRIPTION
**Pull request by danielsz**
Advanced example for System + Sente

* Seamless wiring of components
* No need to specify Sente routes
* Login
* Client-side UI
* Notifications

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Awesome, thanks Daniel!! Much appreciated :-)

**Comment by danielsz** [comment]
Cheers :+1:

**Comment by ptaoussanis** [comment]
Happy to see System's still going strong!

**Comment by danielsz** [comment]
Thank you, Peter! Major version was released today :-) The auto reloading environment is its compelling proposition IMHO.

**Comment by ptaoussanis** [comment]
Oh, great! Just retweeted your announcement. Cheers :-)

On Sun, May 15, 2016 at 12:18 PM, Daniel Szmulewicz <
notifications@github.com> wrote:

> Thank you, Peter! Major version was released today :-) The auto reloading
> environment is its compelling proposition IMHO.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/ptaoussanis/sente/pull/231#issuecomment-219267024>
>



-- 
*Peter Taoussanis*
ptaoussanis@taoensso.com
taoensso.com <https://www.taoensso.com>

**Pull request closed without merging**
