### PR TITLE
Convert code from using cljx to cljc Reader Conditionals

### LINKED ISSUE #149: Switching to reader conditionals and 1.7
What are your thoughts/plans for updating Sente to 1.7 and using cljc? I'm not sure how far back/how long you want to support older versions of Clojure for?

### PR DESCRIPTION
**Pull request by danielcompton**
Fixes #149

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Please note that there's no need to update this PR; I'll fix any merge conflicts while merging.

**Comment by ptaoussanis** [comment]
Merged!

**Comment by danielcompton** [comment]
Hooray!

**Comment by ptaoussanis** [comment]
:-)

**Pull request closed without merging**
