### PR TITLE
Add Aleph adapter

### PR DESCRIPTION
**Pull request by alexandergunnarson**
Continuation of #208 : An adapter for Aleph. Code is heavily borrowed from @ztellman ’s preliminary implementation, but  modified as needed to ensure proper functioning. I’m sure @ztellman can find some holes in it (e.g. with the socket for some reason wanting to close on every message received), but I’ve tested this adapter with the ws and wss sockets I’m using in a remotely deployed test app of mine and it’s been working great so far.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi Alex, thanks for this.

> (e.g. with the socket for some reason wanting to close on every message received)

Sorry just to clarify: that's a hypothetical example, or this actually happens with the implementation in the PR?

**Comment by alexandergunnarson** [comment]
Hey, no problem at all! And that's what actually happened when I didn't comment out the body of `when close-after-send?`. Since it's commented out in the PR, it doesn't happen. The downside of this is that it requires the client to explicitly close a socket (no implicit closing via `close-after-send?`) unless the client gets disconnected or navigates away from the page, in which case of course the socket will be closed anyway. After some playing around with it, it seemed apparent to me that the solution in the PR was the only viable one. I'd be happy for you or @ztellman to prove me wrong, of course.

**Comment by ztellman** [comment]
I'll take a look at the implementation over the next few days.

**Comment by alexandergunnarson** [comment]
Sounds great. Thanks! I probably only changed a few lines of code from your implementation to make it work — the main thing was to fix some arity issues of some anonymous function or other, which was a pain to track down. As I mentioned, this implementation works perfectly for my use case but there may be some who rely heavily on `close-after-send?` — not sure why that's breaking so that's probably the main focus for now.

**Comment by ptaoussanis** [comment]
> As I mentioned, this implementation works perfectly for my use case but there may be some who rely heavily on close-after-send? — not sure why that's breaking so that's probably the main focus for now.

Just have my hands full atm, so haven't looked at any of this - but just want to note that `close-after-send?` support is not optional (it's used for Ajax connections).

**Comment by alexandergunnarson** [comment]
Ah, well I'll look into why that part isn't working then. My use case, of course, is not everyone else's.

**Comment by ztellman** [comment]
I just realized I completely forgot about this.  I guess I don't understand the exact nature of the issue with `close-after-send?`.  @alexandergunnarson, what does it mean that it closes "every time, even with a callback"?

**Comment by alexandergunnarson** [comment]
@ztellman The callback I'm referring to is the callback passed as the third argument to `chsk-send!`.
For instance, from [the example Sente provides](https://github.com/ptaoussanis/sente/blob/master/example-project/src/example/client.cljs):

With callback:
```
(chsk-send! [:example/button2 {:had-a-callback? "indeed"}] 5000
  (fn [cb-reply] (->output! "Callback reply: %s" cb-reply)))
```

Without callback:
```
(chsk-send! [:example/button1 {:had-a-callback? "nope"}])
```

According to the internal logic of Sente (which I can hunt down to give you more context, or @ptaoussanis can tell you more quickly and precisely), if such a callback is not passed, the websocket closes automatically; otherwise, it is left open, awaiting a callback response. This is triggered by `close-after-send?` (the third argument to `-sch-send!`) being passed as true. Ignoring the flag `close-after-send?` flag and keeping the websocket open is normally totally fine (e.g. for my use case), but as @ptaoussanis noted, "close-after-send? support is unfortunately not optional (it's used for Ajax connections)".

Let me know if you want/need further context.

**Comment by ptaoussanis** [comment]
Thanks Alex!

> According to the internal logic of Sente (which I can hunt down to give you more context, or @ptaoussanis can tell you more quickly and precisely), if such a callback is not passed, the websocket closes automatically; otherwise, it is left open, awaiting a callback response. 

Only had a moment to skim this issue, but just want to clarify quickly in case it's useful that this doesn't actually have anything to do with callbacks.

We're talking about Aleph's implementation of [this](https://github.com/ptaoussanis/sente/blob/e1903c0173693d1aa3a0bc35f915ec4186d87a96/src/taoensso/sente/interfaces.cljx#L27) server-side protocol function. It's used to send data to connected clients (might be a WebSocket client or an Ajax client).

For WebSockets: `close-after-send?` will always be false. I.e. we never need/want WebSockets to close after a send.

For Ajax conns: `close-after-send?` will always true. I.e. we want regular HTTP req->resp conns to close after the first response (we're not using chunked transfer encoding, etc.).

Please let me know if there's anything else I can help clarify, will do my best to respond ASAP.

**Comment by alexandergunnarson** [comment]
Thanks @ptaoussanis for your clarification/correction. I haven't been working on the WebSocket-related project I mentioned in probably 3 weeks, so apparently my memory is becoming inaccurate. Either way, callback or not, I remember there definitely being client- and server-side WebSocket support when I was using the Aleph adapter, so there was never an Ajax connection; however, despite this, `close-after-send?` was always true. Thus I simply disabled it in `-sch-send!`. This would sound like something orthogonal to Aleph were it not for the fact that this problem never occurred with e.g. Immutant. 

I will play around with this more, but it might be another few weeks before I get back to that project — sorry.

**Comment by ptaoussanis** [comment]
Closing this to focus on #236

**Pull request closed without merging**
