### PR TITLE
Add host-chsk-url-fn

### PR DESCRIPTION
**Pull request by danielcompton**
It would be helpful for people using cross domain channel sockets to have a simplified `chsk-url-fn` for making connections to different hosts. This PR adds the function, and documentation on how to use it.

### CODE REVIEW

**Comment by danielcompton** [comment]
If you'd prefer fewer functions in the main Sente ns, the other option I thought of was making `default-chsk-fn` take a map of config and return a function. The function would override any config provided by `window-location`, with the initial config provided. This would be a breaking change though, and more complex to use.

**Comment by ptaoussanis** [comment]
Hi Daniel, thanks for this.

As I mentioned last time this came up (in #50), I'm not convinced it makes sense to add any specialised code for the use case you're describing.

An appropriate chsk-url-fn can usually be expressed more flexibly and transparently as a small inline fn, no?

What problem are you actually trying to solve here? Is it that you feel users won't understand how to write an appropriate chsk-url-fn? Could that not better be solved by adding a short cross-domain example to the `default-chsk-url-fn` docstring? (Just trying to understand your motivation better).

Cheers :-)

**Comment by danielcompton** [comment]
I thought that users may not understand how to write the chsk-url-fn correctly. A docstring would be fine too if you'd prefer that.

**Comment by ptaoussanis** [comment]
Okay, going to simplify this. Will keep `:chsk-url-fn` for the moment as an advanced/undocumented feature.

For the simpler common-case that you're describing, have added a `:host` key to the client-side `make-channel-socket!` options. Does that handle your case okay?

**Comment by danielcompton** [comment]
Sure, if you prefer that, I'm happy with any of the options.

**Comment by ptaoussanis** [comment]
Great, closing this then. Change is up on the dev branch and `[com.taoensso/sente "1.6.0-alpha2"]` on Clojars. Cheers :-)

**Pull request closed without merging**
