### PR TITLE
ring-undertow-adapter server adapter added

### PR DESCRIPTION
**Pull request by nikolap**
Sente server adapter for [ring-undertow-adapter](https://github.com/luminus-framework/ring-undertow-adapter).

Let me know or feel free to make any changes as needed.

Thanks to @danboykis for help with the http fallback handler

### CODE REVIEW

**Comment by awb99** [comment]
@nikolaps do you know if it is possible to write an adapter for Jetty?

**Comment by nikolap** [comment]
I don't see why not. Jetty seems to have a [websocket API](https://www.eclipse.org/jetty/documentation/current/jetty-websocket-server-api.html) you can use. There's a standalone implementation [here](https://github.com/Moocar/jetty-websocket/blob/master/jetty-websocket/src/me/moocar/jetty/websocket.clj) you can use as a reference. 

For the HTTP fallback you need to implement the Sente IServerChan interface. If Jetty has a stream implementation you can hook onto it easily. For example, Undertow is pretty easy to do it with, i.e. https://github.com/immutant/immutant/blob/master/web/src/immutant/web/internal/undertow.clj#L178

**Comment by awb99** [comment]
@nikolap Thanks a lot!

**Comment by awb99** [comment]
@nikolap Thanks a lot!

**Comment by yogthos** [comment]
any news on whether this can be merged?

**Comment by nfedyashev** [comment]
Don't want to be that annoying +1-er

but this would really awesome to see this in the master branch at some time in the future.
@nikolap thanks for working on it!

**Comment by ptaoussanis** [comment]
Hey there! Sorry for the delayed response. I'm _really_ limited on time recently - so try to batch my open-source work. Might have an opportunity to try do some later today; if so - will try merge this + cut a new release.

Thanks for the patience!!

**Comment by ptaoussanis** [comment]
Merging manually now, thanks Nik!

**Comment by Ramblurr** [comment]
Is the supported in `[com.taoensso/sente "1.16.0-alpha1"]`? I don't see it mentioned in the docs, but the recent jetty adapter is documented. Just an oversight or not ready yet?

**Comment by ptaoussanis** [comment]
Not ready yet, sorry. Still planning to merge a few more PRs, then cut a new release. Hoping to do w/in the next couple weeks.

**Pull request closed without merging**
