### PR TITLE
Add how to debug Sente websocket in README

### PR DESCRIPTION
**Pull request by arichiardi**
Follow up on https://github.com/ptaoussanis/sente/issues/262.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Thanks, will take a closer look at this next time I'm on Sente!

Cheers :-)

**Comment by arichiardi** [comment]
I will need to add the wrapping to this PR, which I have just recently figurared out and successfully emulated. I was even wondering if it would make sense to extract the part of the `pack` function that adds `+/-` and does the wrapping...but ok we'll discuss that when you'll have time, I got my workaround :smi

**Comment by arichiardi** [comment]
Other section added, I'll leave it here for a double/triple/quadruple check ;)

**Comment by ptaoussanis** [comment]
Hi Andrea-

Sorry for taking so long to get to this, wanted an opportunity to think about it some more.

Appreciate the effort you put into the PR, but I'll be honest - am still hesitant to document implementation details or to encourage folks to depend on them, even for benchmarking.

As I mentioned at https://github.com/ptaoussanis/sente/issues/262#issuecomment-246158984, I'm still not very clear on why one would want to work at a protocol level. Unless there's a strong reason to, would really recommend avoiding it if possible since these details are likely to break unexpectedly one day and without notice.

Am also keen to keep the README as small as possible (it's already on the long side, I think).

As a compromise, have moved your notes to https://gist.github.com/ptaoussanis/848d41c33eb8b4512193ba5e508f961b which we can link to from the FAQ for folks that are interested.

A better long-term solution might be to consider setting up a user Wiki with a proper table of contents, etc. Then we can go into more detail on subjects like this without becoming overwhelming.

Anyway, hope the present solution might be reasonable in the meantime?

**Comment by ptaoussanis** [comment]
Oh, in fact just setup a wiki: https://github.com/ptaoussanis/sente/wiki/Debugging-and-benchmarking-at-the-protocol-level

**Comment by arichiardi** [comment]
Sounds very reasonable, thanks again, agree that this kind of a niche, but it is also good that we now have it :wink:

**Pull request closed without merging**
