### PR TITLE
Allow ClojureScript to act as a server

### PR DESCRIPTION
**Pull request by theasp**
This is the modification to sente to allow ClojureScript to act as a server.  It also introduces the dogfort server adapter and an example project for node.js, both written by Matthew Molly (@whamtet).

The changes to the sente API to allow this is that instead of clj/cljs deciding if sente provides a client or socket, the following was changed:
- `make-channel-socket!` has become `make-channel-socket-server!`
and `make-channel-socket-client!`
- `start-chsk-router!` now has a 3rd argument, `server?`

I am having an issue with the dogfort server adapter and am not sure how you'd like to proceed with it.  Wrapping a few calls in `try` may be all that is needed to fix it.  Perhaps it would be best to strip it out of my pull request and let him submit it, but that would leave us without a working example.  I am going to look into another server.

The following is reproducible by reloading the page several times:
```
phillipsa-lx:/data/phillipsa/projects/sente/node-example-project$ node main.js 
Starting dogfort...
DEBUG [example.my-app-node] - Web server is at http://localhost:5000
DEBUG [example.my-app-node] - Event: [:chsk/uidport-open]
"Unhandled event:" [:chsk/uidport-open]
Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.my-app-node] - Login request: {:user-id "test", :csrf-token "null"}
DEBUG [example.my-app-node] - Login request: {:user-id "test", :csrf-token "null"}
Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}

/data/phillipsa/projects/sente/node-example-project/node_modules/ws/lib/WebSocket.js:218
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/data/phillipsa/projects/sente/node-example-project/node_modules/ws/lib/WebSocket.js:218:16)
    at [object Object].taoensso$sente$interfaces$IAsyncNetworkChannel$send_BANG__STAR_$arity$3 (/data/phillipsa/projects/sente/node-example-project/out/taoensso/sente/server_adapters/dogfort.cljs:27:33)
    at taoensso$sente$interfaces$send_BANG__STAR_ (/data/phillipsa/projects/sente/node-example-project/out/taoensso/sente/interfaces.cljs:11:12)
    at Function.taoensso.sente.interfaces.send_BANG_.cljs$core$IFn$_invoke$arity$variadic (/data/phillipsa/projects/sente/node-example-project/out/taoensso/sente/interfaces.cljs:16:10)
    at taoensso$sente$interfaces$send_BANG_ (/data/phillipsa/projects/sente/node-example-project/out/taoensso/sente/interfaces.cljs:15:1)
    at taoensso$sente$send_buffered_evs_GT_ws_clients_BANG_ (/data/phillipsa/projects/sente/node-example-project/out/taoensso/sente.cljs:575:6)
    at /data/phillipsa/projects/sente/node-example-project/out/taoensso/sente.cljs:357:34
    at /data/phillipsa/projects/sente/node-example-project/out/taoensso/sente.cljs:393:22
    at /data/phillipsa/projects/sente/node-example-project/out/taoensso/sente.cljs:392:17
    at cljs.core.async.impl.dispatch.run.call.taoensso$sente$state_machine__6887__auto____1 (/data/phillipsa/projects/sente/node-example-project/out/taoensso/sente.cljs:392:17)
```

### CODE REVIEW

**Comment by theasp** [comment]
I rearranged the dogfort adapter and added `try` around `.send`.  I can't reproduce my problem and it works now.

**Comment by theasp** [comment]
I have Sente working in express on node as well as dogfort.  Unfortunately there is a small issue with the websocket middleware for express:
https://github.com/HenningM/express-ws/pull/17

**Comment by emnh** [comment]
:+1:  I'm also interested in running sente on node.js.

**Comment by ptaoussanis** [comment]
Hi there,

Is there still interest in this? Can I get a status update on the current PR? Thanks!

**Comment by theasp** [comment]
Hi,

Yes, I am still interested.  The PR works great for me, both server and client.  It currently includes the working adapters for both dogfort and express.  The issue mentioned above in express-ws has been fixed.  Please let me know if you have any questions or want anything changed.

Thanks

**Comment by whamtet** [comment]
Hi Peter,

please pull this request.  Andrew has put my code into a better request that I did :smile:

**Comment by danielcompton** [comment]
I assume you're meaning to close this request, not pull it? (pull is a pretty overloaded word here :))

**Comment by whamtet** [comment]
I meant accept.

**Comment by ptaoussanis** [comment]
Okay, awesome- thanks for confirming. Definitely looks manageable; will try make merging this a priority for v1.8.0. Appreciate all the work that went into this.

Cheers!

**Comment by whamtet** [comment]
No probs!

**Comment by ptaoussanis** [comment]
Hi there,

Thank you both for your patience- have finally made some progress on this.

Just updated the [dev](https://github.com/ptaoussanis/sente/tree/dev) branch and pushed `[com.taoensso/sente "1.8.0-alpha1"]` to Clojars.

This version includes the following changes:
* Sente interfaces no longer assume that clj==server and cljs==client, all interfaces are available to both Clojure and ClojureScript
* Likewise, have introduced the following as per your commit: `make-channel-socket-client!`, `make-channel-socket-server!`, `start-client-chsk-router!`, `start-server-chsk-router!`.

I haven't tested these changes extensively, but they should be ~okay.

If/when you have some time, I'd beg your patience for one further PR update rebased on the current dev branch:
* No changes should be necessary to `sente.cljx` or `interfaces.cljx` 
*  `taoensso.sente.server-adapters.generic-node-ws` will need a minor update for the new disambiguated interface API names
* Would prefer all changes as a single squashed commit

### Re: the example,
Have updated the Sente reference example to use Clojure 1.7+ reader conditionals -

Does that do anything to simplify your task of updating the node example?

If it looks like extensive node-specific changes will still be necessary for the new example, then I think I'd prefer to ask that that be held in a 3rd party repo (outside Sente) that we can link from at https://github.com/ptaoussanis/sente#example-projects

Does that make sense?

Please let me know if you run into any problems and/or if there's anything else I can assist with. Again thank you for all the effort you've both put into this; this PR was invaluable for helping get this stuff in Sente.

**Comment by theasp** [comment]
Looks good.  I should have some time in the next few days to sort this out.  The new example should be no problem now.

**Comment by theasp** [comment]
I've been looking at this a bit tonight.  Would you accept splitting the example into server and client examples?  They would both be in the same project directory, but in src-server and src-client (or src/server & src/client, or whatever).  The issue is that the example still assumes clj is server and cljs is client, so if I put in the code for the node.js webservers it will clash with the client code for the browser.  They need to be in different directories to exclude each other during build. The changes to go from Clojure to ClojureScript for the server side are minimal, especially for dogfort.

As an aside, I had trouble digesting the client & server in the same file when I first tried out Sente.

For now I will copy your example into another repository and if you want it, it can be added later.

**Comment by whamtet** [comment]
Client and server in separate files sounds like a good plan.

**Comment by ptaoussanis** [comment]
Hi Andrew,

Thanks for looking into this.

Sure, would be happy to accept a PR that splits the ref example into `src/server.cljc` and `src/client.cljc`. If possible, would please ask that this be a separate PR from anything to do with node - i.e. that we proceed in two steps:

1. Split the ref example up into 2 namespaces.
2. Add the node server.

Does that seem reasonable / make sense?

**Comment by theasp** [comment]
Sure, no problem at all.

**Comment by theasp** [comment]
Closing for fresh PR.

**Pull request closed without merging**
