### PR TITLE
Create a Channel interface, and add Immutant 2 support

### PR DESCRIPTION
**Pull request by tobias**
See #2.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hey Toby, thanks so much for this - would be very happy to have Immutant support!

Just travelling atm, but will make this a priority when I'm settled. Should be able to take a proper look + get back to you w/in the next couple days.

Cheers! :-)

**Comment by tobias** [comment]
Great! Looking forward to it.

**Comment by ptaoussanis** [comment]
Sorry for the delay - PR looks good to me after a first inspection!

Only change I can suggest at this point is: I'd prefer if we avoid the generic term "channel" for the web-server channel. We've got core.async channels, channel sockets, and web-server channels here - so the term's pretty heavily loaded.

What about `IAsyncNetworkChannel` for the protocol and `hk-ch`->`net-ch` or `nch` for the relevant symbols?

If you can get me an updated PR (to the same feature branch would be perfect), I'll do a local merge and go over the changes in more detail. Barring any unexpected problems there, I'll try get this merged on the dev branch ASAP.

Thanks again for all your efforts, cheers! :-)

**Comment by tobias** [comment]
Thanks for the feedback, and no worries about the delay. That all sounds good to me. I'll take a look at changing the channel names, and try to update the feature branch later today.

**Comment by tobias** [comment]
I just updated the patch and force-pushed it to the feature branch. I went with `IAsyncNetworkChannel` and `net-ch` (that felt clearer to me than `nch`). Let me know if you need anything else.

**Comment by ptaoussanis** [comment]
On this today.

**Comment by ptaoussanis** [comment]
Hey Toby,

Have merged this PR on the [dev](https://github.com/ptaoussanis/sente/tree/dev) branch and released to Clojars as `[com.taoensso/sente "1.4.0-alpha1"]`.

Made some superficial mods to the PR [here](https://github.com/ptaoussanis/sente/commit/268fb89894e712ef81164dd1d95ad4bbb2636293). 

Did end up adding an adapter interface to avoid the `provide-as-channel!`, `when-import` stuff. The current interface proposal is [here](https://github.com/ptaoussanis/sente/blob/268fb89894e712ef81164dd1d95ad4bbb2636293/src/taoensso/sente/interfaces.cljx) with the server implementations [here](https://github.com/ptaoussanis/sente/tree/268fb89894e712ef81164dd1d95ad4bbb2636293/src/taoensso/sente/server_adapters).

Does that seem reasonable to you?

Ran some quick tests with both http-kit & Immutant, though I've never used Immutant before so would appreciate a confirmation that it's working as expected with the Clojars release?

If you've got no objections, will publish a (dev) release so that folks can start testing it out. Thanks again for all your work+input on this! Cheers :-)

**Comment by ptaoussanis** [comment]
Had some time this morning so ended up just cutting an [early release](https://github.com/ptaoussanis/sente/releases/tag/v1.4.0-alpha1).

Closing this PR since it's essentially merged, but please feel free to ping with any issues/thoughts you may have with the v1.4.0-alpha1 release.

Cheers!

**Comment by tobias** [comment]
Peter:

Thanks for merging this in, and for putting in the extra work to get rid of `provide-as-channel!` - I like the channel adapter approach.

1.4.0-alpha1 works with well with the Immutant incremental build listed in `example-project/project.clj` after fixing a small typo in `my_app.clj`. However, we recently made a change to Immutant's async API which breaks the Immutant server adapter as it is currently implemented. We plan on releasing an Immutant beta in the next few days; once that happens, that API will be stable, and I can update Sente at that point.

I noticed you gave me push rights - would you be opposed to me pushing strictly Immutant related fixes? I can fix the typo in the example project on `master`, and fix the server adapter on `dev` (once we have Immutant beta2 out). If you would still prefer pull requests, I'm perfectly fine with that.

**Comment by ptaoussanis** [comment]
Great, thanks for the follow up.

> We plan on releasing an Immutant beta in the next few days; once that happens, that API will be stable, and I can update Sente at that point.

No problem, sounds good.

> I noticed you gave me push rights - would you be opposed to me pushing strictly Immutant related fixes? 

Oh if it's an obvious fix/typo/etc. (Immutant or otherwise), feel free to just go ahead.

**Pull request closed without merging**
