### PR TITLE
Add documentation for custom Transit handlers

### PR DESCRIPTION
**Pull request by danielcompton**
This was taken from
https://github.com/ptaoussanis/sente/pull/90#issuecomment-137334748

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Merged, thanks!

**Comment by Frozenlock** [comment]
@danielcompton Would you mind describing in a little more details?

I get the following error on my client when I add the `joda-time-writer` stuff on the server:
```js
Uncaught #error {:message "Malformed event (wrong type). Event should be of `[ev-id ?ev-data]` form: ~:chsk/handshake", :data {:malformed-event "~:chsk/handshake"}}
```

**Comment by danielcompton** [comment]
@Frozenlock just saw this, but it looks like the data is not being decoded correctly?

**Comment by Frozenlock** [comment]
@danielcompton I can't exactly remember what was happening :stuck_out_tongue: I'll ping you if I ever encounter this again.

**Pull request closed without merging**
