### PR TITLE
Convert code from using cljx to cljc Reader Conditionals

### LINKED ISSUE #149: Switching to reader conditionals and 1.7
What are your thoughts/plans for updating Sente to 1.7 and using cljc? I'm not sure how far back/how long you want to support older versions of Clojure for?

### PR DESCRIPTION
**Pull request by danielcompton**
This isn't ready for merging, I'm opening a PR early to get feedback on style.

I've converted the CLJX code to cljc. There are sections here which aren't strictly platform dependent and could have the reader conditionals removed, but the reader conditionals/cljx expressions help delineate the client and server API. That may change in the future if there are CLJ Sente clients, but for now it's fine as is.

I'm mostly interested in your feedback on the the conversion, and if you're happy with how the patch is looking. I'll do some testing shortly.

You can use [?w=0](https://github.com/ptaoussanis/sente/pull/232/files?w=0) to look at the changes and ignore whitespace diffs.

Fixes #149

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi Daniel, thanks for this! Just skimmed quickly, but style looks good.

Please do note that as I mentioned at https://github.com/ptaoussanis/sente/issues/149#issuecomment-219275289, will be up for a .cljx->.cljc merge only after the release of v1.9 since the codebase is currently unstable and will still be undergoing dev work until then.

Might suggest you hold off conversion efforts until the codebase has stabilized?

**Comment by danielcompton** [comment]
Ah whoops, forgot about that, jumped in in haste. Will pause till then.

**Comment by ptaoussanis** [comment]
Thanks, just want to make sure you don't waste any of your efforts. Definitely onboard for the cljc conversion soon.

**Comment by ptaoussanis** [comment]
@danielcompton Hey Daniel, finally had some time to cut the v1.9 beta. Let's maybe give it a week or two; if there's no unexpected problems, will switch to release candidate status and the final release soon after.

Will be ready to merge an updated cljx->cljc PR soon as v1.9 final is out the door. Know you've been waiting for this for a while already.

Cheers :-)

**Comment by ptaoussanis** [comment]
Okay, v1.9 final is out - I'm ready for an updated .cljc port whenever you are. Thanks again!

**Comment by danielcompton** [comment]
Continuing in #242.

**Pull request closed without merging**
