### PR TITLE
Server adapter for Macchiato Framework on Node.js

### PR DESCRIPTION
**Pull request by theasp**
https://macchiato-framework.github.io/

This needs the following to have a working session, and csrf token:
https://github.com/macchiato-framework/macchiato-core/pull/20

### CODE REVIEW

**Comment by theasp** [comment]
Example is here: https://github.com/theasp/sente-nodejs-example/tree/macchiato

**Comment by theasp** [comment]
@ptaoussanis Hi Peter, I'm sure you are just busy, but is there anything I can do to move this PR along?

**Comment by ptaoussanis** [comment]
Hi @theasp,

Merging this seems to cause `lein cljsbuild once` to fail with:

```
Caused by: clojure.lang.ExceptionInfo: No such namespace: macchiato.middleware.anti-forgery, could not locate macchiato/middleware/anti_forgery.cljs, macchiato/middleware/anti_forgery.cljc, or JavaScript source providing "macchiato.middleware.anti-forgery" (Please check that namespaces with dashes use underscores in the ClojureScript file name) in file src/taoensso/sente/server_adapters/macchiato.cljs {:tag :cljs/analysis-error}
```

Am unfortunately a little short on time so can't look closer to debug; could you please advise?

Thanks!

**Comment by theasp** [comment]
Hi @ptaoussanis, it just needed a dep on `macchiato/core` for `:dev`.

**Comment by ptaoussanis** [comment]
Thanks, merged :+1:

**Pull request closed without merging**
