### PR TITLE
Updated dependences for 1.11.1 version

### LINKED ISSUE #314: Had to remove a dependency to start example project
In order to start the example project, I had to remove `[com.cemerick/austin "0.1.6"]` from `project.clj`. Otherwise, I get
`Caused by: java.io.FileNotFoundException: Could not locate cemerick/piggieback__init.class or cemerick/piggieback.clj on classpath.`

### PR DESCRIPTION
**Pull request by theasp**
This fixes #314 and #311

### CODE REVIEW

**Comment by danielcompton** [comment]
This seems reasonable to me, I'll merge in a few days unless @ptaoussanis has any objections.

**Comment by ptaoussanis** [comment]
Thanks Andrew, Daniel- looks good!

Small request: would prefer if we bump the `minor` (x.**y**.z) version number for substantial dependency updates (since there's some non-zero potential for unexpected breakage).

Will try merge this and cut a new Clojars release later this week :+1:

(Also still owe you both an email reply, haven't forgotten- apologies for the delay).

**Comment by theasp** [comment]
I've updated it to 1.12.0.  No worries, glad you aren't dead! :)

**Comment by ptaoussanis** [comment]
Merging manually now, thanks again!

**Comment by ptaoussanis** [comment]
Merged, and cut `v1.12.0` [on Clojars](https://clojars.org/com.taoensso/sente) :+1: 

Please note that I removed some whitespace changes, and split the dep bumps and version bump into separate commits.

**Pull request closed without merging**
