### PR TITLE
Pick up handshake-user-data from websocket message into :chsk/state

### PR DESCRIPTION
**Pull request by whodidthis**
#110

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hey there,

What's your motivation for this? Any reason you wouldn't just watch the `:chsk/handshake` event for this data?

**Comment by whodidthis** [comment]
Sorry, I've not seen a `:chsk/handshake` coming from ch-recv at least. Just tried the example project. I might be confused about some stuff again

**Comment by ptaoussanis** [comment]
> Sorry, I've not seen a :chsk/handshake coming from ch-recv at least

Aha, that's because it won't! My mistake, thought it would :-)

Your solution seems reasonable but would like to sleep on it. Will get back to you about this.

**Comment by whodidthis** [comment]
Oh, yeah just looked at the source again and it's there https://github.com/ptaoussanis/sente/blob/dev/src/taoensso/sente.cljx#L28. I guess it's currently like `:chsk/ws-ping` in that it isn't put! into ch-recv. I'm all for not merging handshake-user-data into chsk-state if I can handle `:chsk/handshake` myself. :+1:

**Comment by ptaoussanis** [comment]
Okay, have just updated `[com.taoensso/sente "1.4.0-SNAPSHOT"]` on Clojars. This should put `:chsk/handshake` evs to your client-side `ch-recv` as originally intended.

Details in the [dev changelog](https://github.com/ptaoussanis/sente/blob/dev/CHANGELOG.md).

Please let me know how this one goes?

Cheers! :-)

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/sente "1.4.0-beta1"]` to Clojars. Closing for now, feel free to reopen if you run into any issues.

**Pull request closed without merging**
