### PR TITLE
Split example to client & server

### PR DESCRIPTION
**Pull request by theasp**
As discussed in #168.  Let me know if this is acceptable.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Merging to take a closer look, thanks! Will let you know once I'm ready for the node PR :-)

**Comment by ptaoussanis** [comment]
Hi Andrew, that was helpful - thank you!

Have the updated example project up at https://github.com/ptaoussanis/sente/tree/dev/example-project. **Am ready for the node PR when you are**.

### Re: the node example

After taking a closer look at the split client/server namespaces, it occurs to me that it'd probably be best (simplest) if we just kept the separate client/server namespaces as `client.cljs` and `server.clj` for at least the short term until it becomes clear how many folks are going to be interested in a cljs-based server.

How would you feel if you include the node example as an entry at https://github.com/ptaoussanis/sente/tree/dev#example-projects? You could set up a separate repo for this with a `client.cljs` and `server.cljs` (your preference, of course).

**Comment by theasp** [comment]
I am perfectly fine with hosting a fork of the example.  Hopefully someone will poke me if the API changes.

**Comment by ptaoussanis** [comment]
Not expecting any major changes; Sente's always been pretty stable and I'm pretty happy with the current API. 

If there are ever any unexpected changes, will also try keep backwards compatibility when possible.

**Pull request merged**
